# Generated by Django 4.1.5 on 2023-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_usedetails_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_link',
            field=models.CharField(default='104ab42f11', max_length=100),
            preserve_default=False,
        ),
    ]
